# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GreenPeas' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod "Cards", :git => 'https://github.com/PaoloCuscela/Cards.git'
  pod "SnapKit", "~> 4.0.0"
  pod 'Floaty', '~> 4.1.0'
  pod 'CBZSplashView', '~> 1.0.0'
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  # Pods for GreenPeas

end
